
@startuml

Class Application {

}

Class Membre {
    - Int id  
    # String Indentifiant 
    # String Mail   
    # String role = Membre     
}

Class UIManager {
    # Int IdOeuvre
    # deleteMembre()

}

Class DataM{
    - Int idMember
    - String Key
    # String Username
    # String Lastname
    # String Firstname
    # String mail
    -- encrypted --
    - String password
 

}


Membre <-o Application : manage 
Application -> UIManager : informe
UIManager-> DataM : connection
@enduml